---
  - include_role:
      name: pre_install_checks
  - name: Check if google perf kit is already installed
    stat:
      path: /opt/googleperfkit
    register: application_directory
  - name: Download master branch of GooglePerfkit and unzip
    unarchive:
      src: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/archive/master.zip
      dest: /opt/
      remote_src: yes
    when: application_directory.stat.exists == false
  - name: Rename downloaded archive
    command: mv /opt/PerfKitBenchmarker-master /opt/googleperfkit
    when: application_directory.stat.exists == false
  - copy:
      src: '{{ playbook_dir }}/../benchmarks.yml'
      dest: /root/benchmarks.yml
  - copy:
      src: '{{ playbook_dir }}/../benchmarks.py'
      dest: /root/benchmarks.py
  - name: Create result and log directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
    with_items:
      - /opt/results
      - /opt/logs
  - name: Enable epel-release
    command: yum install epel-release -y
  - name: Install npm
    command: yum install npm -y
  - name: Install GCC
    command: yum install gcc -y
  - name: Install python pip
    command: yum install python-pip -y
    become: yes
  - name: Upgrade pip and install pip packages
    pip:
      name: "pip"
      state: latest
    become: true
  - name: Uninstall incompatiable pip packages
    command: pip uninstall pyOpenSSL cryptography
  - name: Install Azure client
    shell: npm install azure-cli@0.10.4 -g
    become: yes
  - name: Install doctl for digital ocean
    unarchive:
      src: https://github.com/digitalocean/doctl/releases/download/v1.10.0/doctl-1.10.0-linux-amd64.tar.gz
      dest: /usr/local/bin
      remote_src: yes
  - name: Patch open stack requirements file
    lineinfile:
      path: /opt/googleperfkit/requirements.txt
      regexp: "{{ item.old }}"
      line: "{{ item.new }}"
      backup: yes
    with_items:
    - { old: 'PyYAML==3.12', new: 'PyYAML==3.13' }
  - name: Uninstall yum managed PyYAML version
    command: yum remove PyYAML -y
  - name: Install colorama patch newer version
    command: pip install colorama==0.3.9
  - name: Install python-devel
    command: yum install python-devel -y
  - name: Install requirements via pip
    command: pip install -r {{ item }}
    args:
      chdir: /opt/googleperfkit
    with_items:
      - perfkitbenchmarker/providers/openstack/requirements.txt
      - perfkitbenchmarker/providers/aws/requirements.txt
    become: true
  - name: API key configuration and validation and run benchmarks
    command: python {{ playbook_dir }}/../authenticate_api_keys.py
